### ISSUE TITLE
[Question] PATH

### ISSUE THREAD

**Issue by lonix1** [weareinteractive/ansible-environment#16]
Is it possible to somehow use this role to EDIT (rather than add) to the environment?

Specifically, I would like to add to `$PATH`, but what actually happens is the existing one is overwritten.

I also tried `PATH: "$PATH:/foo/bar/"`

**Comment by franklinkim** [comment]
Hi, you can edit/replace the existing `PATH` definition as such:

```yaml
---
- hosts: all
  roles:
    - weareinteractive.environment
  vars:
    environment_config:
      PATH: "/foo/bar:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games/"
```

But you can't add another `PATH` definition as it's using the `lineinfile` module.

Hope this helps
